
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import React from "react";
const { lazy } = React;
import { RouteObject } from "react-router-dom";
import { UserGuard } from "app";
import { SuspenseWrapper } from "./prod-components/SuspenseWrapper";

const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const ScriptGeneration = lazy(() => import("./pages/ScriptGeneration.tsx"));
const StoryAcquisition = lazy(() => import("./pages/StoryAcquisition.tsx"));
const StoryDetails = lazy(() => import("./pages/StoryDetails.tsx"));
const VoiceOver = lazy(() => import("./pages/VoiceOver.tsx"));

export const userRoutes: RouteObject[] = [
	{ 
		path: "/", 
		element: <SuspenseWrapper><App /></SuspenseWrapper>
	},
	{ 
		path: "/dashboard", 
		element: <SuspenseWrapper><UserGuard><Dashboard /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/login", 
		element: <SuspenseWrapper><Login /></SuspenseWrapper>
	},
	{ 
		path: "/logout", 
		element: <SuspenseWrapper><UserGuard><Logout /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/script-generation", 
		element: <SuspenseWrapper><UserGuard><ScriptGeneration /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/scriptgeneration", 
		element: <SuspenseWrapper><UserGuard><ScriptGeneration /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/story-acquisition", 
		element: <SuspenseWrapper><UserGuard><StoryAcquisition /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/storyacquisition", 
		element: <SuspenseWrapper><UserGuard><StoryAcquisition /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/story-details", 
		element: <SuspenseWrapper><UserGuard><StoryDetails /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/storydetails", 
		element: <SuspenseWrapper><UserGuard><StoryDetails /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/voice-over", 
		element: <SuspenseWrapper><UserGuard><VoiceOver /></UserGuard></SuspenseWrapper>
	},
	{ 
		path: "/voiceover", 
		element: <SuspenseWrapper><UserGuard><VoiceOver /></UserGuard></SuspenseWrapper>
	},
];
