name: ESLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install Dependencies
        run: |
          cd frontend
          yarn install
          
      - name: Run ESLint
        run: |
          cd frontend
          yarn lint || true  # Don't fail the build if there are linting errors
